src/Web/Controllers/CreditCardsController.cs
namespace SoppingCartStore.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using ShoppingCartStore.Common.BindingModels.CreditCard;
    using ShoppingCartStore.Common.Constants;
    using ShoppingCartStore.Models;
    using ShoppingCartStore.Services.DataServices;
    using System.Threading.Tasks;

    [Authorize]
    public class CreditCardsController : Controller
    {
        private ICreditCardService creditCardService;
        private UserManager<Customer> userManager;

        public CreditCardsController(ICreditCardService creditCardService, UserManager<Customer> userManager)
        {
            this.creditCardService = creditCardService;
            this.userManager = userManager;
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCreditCardBindingModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            await this.creditCardService.Create(model, this.User.Identity.Name);

            return this.RedirectToAction(ActionConstants.Index, ControllerConstants.CreditCards);
        }

        public async Task<IActionResult> Index()
        {
            string customerId = (await userManager.FindByNameAsync(this.User.Identity.Name)).Id;
            var creditCards = await this.creditCardService.GetAllCreditCardsAsync(customerId);
            return View(creditCards);
        }
    }
}

src/Web/Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShoppingCartStore.Common.BindingModels.Product;
using ShoppingCartStore.Common.Constants;
using ShoppingCartStore.Common.ViewModels.Product;
using ShoppingCartStore.Services.DataServices;

namespace SoppingCartStore.Web.Controllers
{
    public class ProductsController : Controller
    {
        private IProductService _productService;
        private ICartService _cartService;

        public ProductsController(ICartService cartService, IProductService productService)
        {
            _productService = productService;
            _cartService = cartService;
        }

        public IActionResult Index(FilterBindingModel model)
        {
            IEnumerable<ProductViewModel> products;

            // TODO: Encapsulate business logic in service layer
            if (model.CategoryIdFilter != null || model.BrandIdFilter != null 
                || model.SearchFilter != null)
            {
                products = _productService.GetAllViewModelsFilteredAsync(model);
            }
            else
            {
                products = _productService.GetAllViewModelsAsync();
            }

            return View(products);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductBindingModel model)
        {
            await _productService.CreateAsync(model);
            return this.RedirectToAction(ActionConstants.Index, ControllerConstants.Products);
        }

        public async Task<IActionResult> Details(string id)
        {
            var productViewModel = _productService.FindById(id);
            return View(productViewModel);
        }
    }
}

src/Web/Views/Shared/_AdministratorPartial.cshtml
@if (User.IsInRole("Administrator"))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-page="/Categories/Create">
            <button class="btn btn-sm btn-info">Create Category</button>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-page="/Brands/Create">
            <button class="btn btn-sm btn-info">Create Brand</button>
        </a>
    </li>
}

src/Web/Views/Shared/_BalancePartial.cshtml
@if (User.IsInRole("Administrator"))
{
    @await Component.InvokeAsync("Balance")
}

src/Web/Views/Shared/_CartPartial.cshtml
@{
    ViewData["Title"] = "Main Header";
}

<section class="col-lg-1 col-xs-12">
    @await Component.InvokeAsync("Cart")
</section>

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SoppingCartStore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

    @* FONT AWESOME *@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-xl navbar-toggleable-xl navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-xl-inline-flex flex-xl-row-reverse">
                    <ul class="navbar-nav">

                        <partial name="_AdministratorPartial" />
                        <partial name="_BalancePartial" />
                        <partial name="_LoginPartial" />
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Create">Create Product</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" id="navbarDropdown" role="button" data-toggle="dropdown"
                                   aria-haspopup="true" aria-expanded="false">
                                    Credit Cards
                                </a>
                                <div class="dropdown-menu" aria-labelledby="customersDropdown">
                                    <a class="dropdown-item" asp-controller="CreditCards" asp-action="Index">My Cards</a>
                                    <a class="dropdown-item" asp-controller="CreditCards" asp-action="Create">Create Card</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Deposit/Create">Deposit</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Withdraw/Index">Withdraw</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Transactions/Index">Transactions</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - SoppingCartStore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Web/Views/Shared/_SearchForm.cshtml
<form method="get" asp-action="Index" asp-controller="Products">
    <div class="row">
        <div class="col-sm-12 col-lg-4">
            @await Component.InvokeAsync("Categories")
        </div>
        <div class="col-sm-12 col-lg-4">
            @await Component.InvokeAsync("Brands")
        </div>
        <div class="col-sm-12 col-lg-4">
            <h5>Search:</h5>
            <div class="row">
                <div class="col-lg-8">
                    <input name="SearchFilter" class="form-control mr-sm-2 " type="search" placeholder="By name" aria-label="Search">
                </div>
                <div class="col-lg-4">
                    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
                </div>
            </div>
        </div>
    </div>
</form>

src/Web/Views/Shared/_Sidebar.cshtml
<aside class="mb-2">
    <h3 class="text-center">Wishlist</h3>
    <hr class="bg-info h-2">
    <div class="text-center">
        @if (User.Identity.IsAuthenticated)
        {
            @await Component.InvokeAsync("Wishlist")
        }
        else
        {
            <i class="text-secondary">Sign in to view you wishlist</i>
        }
    </div>
    <hr class="bg-info" />
</aside>